# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'moodlog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for moodlog
  pod 'Alamofire', '~> 5.8.1'
  pod 'DGCharts', '~> 5.1'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.shell_script_build_phases.each do |phase|
        phase.shell_script = "chmod +x \"${PODS_ROOT}/#{phase.shell_script}\" && #{phase.shell_script}"
      end
      # Set deployment target for all pods to iOS 15.0
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end